buckets                   = ["s3-storage-for-images", "s3-storage-for-videos"]
tags                      = "s3-bucket"
envs                      = "staging-env"
bucket_versioning_enabled = "Disabled"
eks_cluster_name          = "staging-eks-cluster"
eks_cluster_version       = "1.34"
eks_ec2_instance_types    = ["t3.medium"]
eks_asg_desired_size      = 2
eks_asg_max_size          = 5 # supposed to be bigger number
eks_asg_min_size          = 1
